#pragma once

// Switch Printer — Mainsail-style Web Dashboard (textContent-safe, POST CSRF-protected)
// Temperature thresholds must match config.h: 190/120/40, max 300/120
static const char *WEB_INDEX_HTML =
"<!DOCTYPE html><html lang=\"zh\"><head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">"
"<title>Switch Printer</title>"
"<style>"
":root{--bg:#0a0d14;--ca:#141824;--bd:#1e2332;--tx:#e8eaed;--di:#5c6370;"
"--ac:#2a6ff8;--ru:#f0a040;--ok:#40c860;--er:#e04040;--wa:#e0c040;"
"--co:#4080e0;--wm:#e0a040;--ht:#e04040;--rd:10px;--gp:8px}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,-apple-system,sans-serif;background:var(--bg);"
"color:var(--tx);min-height:100vh;overflow-x:hidden}"
".hd{display:flex;align-items:center;gap:10px;padding:12px 14px;"
"background:linear-gradient(180deg,#1a1f30,#0f1320);border-bottom:1px solid var(--bd)}"
".hd .dot{width:10px;height:10px;border-radius:50%;flex-shrink:0;transition:.3s}"
".hd .dot.off{background:var(--er);box-shadow:0 0 6px var(--er)}"
".hd .dot.ok{background:var(--ok);box-shadow:0 0 8px var(--ok)}"
".hd .dot.run{background:var(--ru);box-shadow:0 0 10px var(--ru);animation:pl 1.2s infinite}"
"@keyframes pl{50%{opacity:.35}}"
".hd h1{font-size:.95rem;font-weight:600;letter-spacing:.03em;flex:1}"
".hd .ip{font-size:.65rem;color:var(--di)}"
".gs{display:grid;grid-template-columns:1fr 1fr;gap:var(--gp);padding:10px 12px;max-width:420px;margin:0 auto}"
".gg{background:var(--ca);border-radius:var(--rd);padding:12px;text-align:center;border:1px solid var(--bd)}"
".gg svg{width:100%;max-width:130px;display:block;margin:0 auto}"
".sb{display:flex;gap:6px;padding:0 12px 8px}"
".st{flex:1;background:var(--ca);border-radius:var(--rd);padding:10px;text-align:center;border:1px solid var(--bd)}"
".st .v{font-weight:700;font-size:.85rem}"
".st .l{font-size:.58rem;color:var(--di);text-transform:uppercase;letter-spacing:.08em}"
".ps{padding:0 12px 10px}"
".pb{background:var(--bd);border-radius:20px;height:10px;overflow:hidden;position:relative}"
".pb div{background:linear-gradient(90deg,var(--ac),var(--ok));height:100%;"
"border-radius:20px;transition:width .5s}"
".pb div.run{background:linear-gradient(90deg,var(--ac),var(--ru));animation:sh 2s infinite}"
"@keyframes sh{0%{filter:brightness(1)}50%{filter:brightness(1.3)}100%{filter:brightness(1)}}"
".pi{display:flex;justify-content:space-between;font-size:.65rem;color:var(--di);margin-top:4px}"
".ct{display:grid;grid-template-columns:repeat(4,1fr);gap:var(--gp);padding:0 12px 10px}"
".ct button,.jb button,.zu button{background:var(--ca);color:var(--tx);"
"border:1px solid var(--bd);border-radius:var(--rd);cursor:pointer;"
"font-family:inherit;transition:.12s;-webkit-tap-highlight-color:transparent;"
"display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px}"
".ct button{padding:11px 6px;font-size:.7rem}"
".ct button:active,.jb button:active,.zu button:active{transform:scale(.94);background:#1e2335}"
".ct .ic{font-size:1.2rem;line-height:1}"
".ct .stp{color:var(--er);border-color:rgba(224,64,64,.35)}"
".ct .stp:active{background:rgba(224,64,64,.12)}"
".ct .go{color:var(--ok);border-color:rgba(64,200,96,.35)}"
".jp{padding:0 12px 10px}"
".jb{display:grid;grid-template-columns:1fr 1fr 1fr;grid-template-rows:1fr 1fr 1fr;"
"gap:5px;max-width:240px;margin:0 auto}"
".jb button{padding:10px 4px;font-size:.75rem;min-height:40px}"
".jb .cx{grid-column:2;grid-row:2;color:var(--di);font-size:.65rem}"
".zu{display:flex;gap:var(--gp);padding:0 12px 10px;justify-content:center}"
".zu button{padding:8px 16px;font-size:.72rem}"
".up{padding:0 12px 10px;display:flex;gap:8px}"
".up input[type=file]{flex:1;background:var(--ca);color:var(--tx);padding:9px 10px;"
"border-radius:var(--rd);border:1px dashed var(--bd);font-size:.72rem;font-family:inherit;cursor:pointer;min-width:0}"
".up input::file-selector-button{background:var(--bd);color:var(--tx);"
"border:none;padding:5px 12px;border-radius:5px;cursor:pointer;font-family:inherit;margin-right:8px}"
".up button{background:var(--ok);color:#000;border:none;padding:9px 16px;"
"border-radius:var(--rd);font-weight:600;font-size:.72rem;cursor:pointer;font-family:inherit;white-space:nowrap}"
".up button:active{opacity:.8}"
".lg{background:#060911;margin:0 12px 12px;padding:8px 10px;border-radius:8px;"
"height:140px;overflow-y:auto;font-family:'Courier New',monospace;font-size:.6rem;"
"color:var(--di);border:1px solid #151a25;line-height:1.45}"
".lg .sn{color:#3a6fa8}.lg .rv{color:#3a8850}.lg .er{color:var(--er)}"
".lg .ts{color:#333d50}"
".fn{padding:0 12px;font-size:.65rem;color:var(--ru);text-align:center;"
"white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-bottom:4px}"
".s-idle{color:var(--ok)}.s-printing{color:var(--ru)}"
".s-paused{color:var(--wa)}.s-error{color:var(--er)}.s-offline{color:var(--di)}"
"@media(min-width:768px){body{max-width:620px;margin:0 auto}"
".gs{max-width:380px}.jb{max-width:220px}}"
"@media(min-width:1024px){body{max-width:900px}}"
"</style></head><body>"
"<div class=\"hd\">"
"<div class=\"dot off\" id=\"dot\"></div>"
"<div><h1>Switch 3D Printer</h1><div class=\"ip\" id=\"ip-txt\">Waiting...</div></div>"
"</div>"
"<div class=\"gs\">"
"<div class=\"gg\">"
"<svg viewBox=\"0 0 120 120\">"
"<circle cx=\"60\" cy=\"60\" r=\"48\" fill=\"none\" stroke=\"var(--bd)\" stroke-width=\"7\"/>"
"<circle id=\"nr\" cx=\"60\" cy=\"60\" r=\"48\" fill=\"none\" stroke=\"var(--co)\" "
"stroke-width=\"7\" stroke-linecap=\"round\" stroke-dasharray=\"0 301\" "
"transform=\"rotate(-90 60 60)\" style=\"transition:stroke-dasharray .6s,stroke .6s\"/>"
"<text x=\"60\" y=\"57\" text-anchor=\"middle\" fill=\"var(--tx)\" "
"font-size=\"26\" font-weight=\"700\" id=\"nv\">--</text>"
"<text x=\"60\" y=\"76\" text-anchor=\"middle\" fill=\"var(--di)\" "
"font-size=\"11\" id=\"nt\"></text>"
"<text x=\"60\" y=\"102\" text-anchor=\"middle\" fill=\"var(--di)\" "
"font-size=\"10\" letter-spacing=\".15em\">NOZZLE</text></svg></div>"
"<div class=\"gg\">"
"<svg viewBox=\"0 0 120 120\">"
"<circle cx=\"60\" cy=\"60\" r=\"48\" fill=\"none\" stroke=\"var(--bd)\" stroke-width=\"7\"/>"
"<circle id=\"br\" cx=\"60\" cy=\"60\" r=\"48\" fill=\"none\" stroke=\"var(--co)\" "
"stroke-width=\"7\" stroke-linecap=\"round\" stroke-dasharray=\"0 301\" "
"transform=\"rotate(-90 60 60)\" style=\"transition:stroke-dasharray .6s,stroke .6s\"/>"
"<text x=\"60\" y=\"57\" text-anchor=\"middle\" fill=\"var(--tx)\" "
"font-size=\"26\" font-weight=\"700\" id=\"bv\">--</text>"
"<text x=\"60\" y=\"76\" text-anchor=\"middle\" fill=\"var(--di)\" "
"font-size=\"11\" id=\"bt\"></text>"
"<text x=\"60\" y=\"102\" text-anchor=\"middle\" fill=\"var(--di)\" "
"font-size=\"10\" letter-spacing=\".15em\">BED</text></svg></div></div>"
"<div class=\"sb\">"
"<div class=\"st\"><div class=\"v s-offline\" id=\"state-txt\">Offline</div><div class=\"l\">State</div></div>"
"<div class=\"st\"><div class=\"v\" id=\"prog-pct\">0%</div><div class=\"l\">Progress</div></div>"
"<div class=\"st\"><div class=\"v\" id=\"lines-info\">--</div><div class=\"l\">Lines</div></div></div>"
"<div class=\"fn\" id=\"file-name\"></div>"
"<div class=\"ps\">"
"<div class=\"pb\"><div id=\"prog-fill\" style=\"width:0%\"></div></div>"
"<div class=\"pi\"><span id=\"time-info\">--</span><span id=\"eta-info\"></span></div></div>"
"<div class=\"ct\">"
"<button onclick=\"api('home')\"><span class=\"ic\">Home</span></button>"
"<button onclick=\"api('pause')\"><span class=\"ic\">Pause</span></button>"
"<button onclick=\"api('resume')\" class=\"go\"><span class=\"ic\">Resume</span></button>"
"<button onclick=\"api('cancel')\" class=\"stp\"><span class=\"ic\">Stop</span></button></div>"
"<div class=\"jp\"><div class=\"jb\">"
"<button style=\"grid-column:2;grid-row:1\" onclick=\"move('y',10)\">Y+</button>"
"<button style=\"grid-column:1;grid-row:2\" onclick=\"move('x',-10)\">X-</button>"
"<div class=\"cx\">HOME</div>"
"<button style=\"grid-column:3;grid-row:2\" onclick=\"move('x',10)\">X+</button>"
"<button style=\"grid-column:2;grid-row:3\" onclick=\"move('y',-10)\">Y-</button>"
"</div></div>"
"<div class=\"zu\">"
"<button onclick=\"move('z',1)\">Z+1</button>"
"<button onclick=\"api('home')\">Z Home</button>"
"<button onclick=\"move('z',-1)\">Z-1</button></div>"
"<div class=\"up\">"
"<input type=\"file\" id=\"gcode-file\" accept=\".gcode,.gco,.nc\">"
"<button onclick=\"uploadFile()\">Upload & Print</button></div>"
"<div class=\"lg\" id=\"log\"><span class=\"ts\">--:--:--</span> Waiting for printer...</div>"
// P0: textContent replaces innerHTML (SEC-004 XSS), POST for mutating APIs (SEC-003 CSRF)
"<script>"
"var prt=0,elt=0;"
"function api(c){var m=(c==='status')?'GET':'POST';"
"fetch('/api/'+c,{method:m}).then(function(r){return r.json()}).then(function(d){"
"log(d.msg||d.error||c)})}"
"function move(a,d){fetch('/api/move?axis='+a+'&dist='+d,{method:'POST'})"
".then(function(r){return r.json()}).then(function(d){log(d.msg)})}"
"function uploadFile(){var f=document.getElementById('gcode-file').files[0];"
"if(!f)return;var fd=new FormData();fd.append('file',f);"
"log('Upload: '+f.name+' ('+(f.size/1e6).toFixed(1)+' MB)');"
"fetch('/upload',{method:'POST',body:fd}).then(function(r){return r.json()})"
".then(function(d){log(d.msg||d.error)})}"
// textContent-safe logging (no innerHTML)
"var lgEl=document.getElementById('log');"
"function log(m){var t=new Date().toLocaleTimeString();"
"var d=document.createElement('div');"
"var ts=document.createElement('span');ts.className='ts';ts.textContent=t;"
"d.appendChild(ts);d.appendChild(document.createTextNode(' '+m));"
"lgEl.appendChild(d);lgEl.scrollTop=lgEl.scrollHeight;"
"if(lgEl.children.length>200)lgEl.firstChild.remove()}"
// Temp ring update (thresholds: 190/120/40, max 300/120 — match config.h)
"function updateRing(el,temp,max,elV,elT){var ratio=Math.min(temp/max,1);"
"var circ=301;var dash=ratio*circ;"
"el.setAttribute('stroke-dasharray',dash+' '+(circ-dash));"
"var clr='var(--co)';if(temp>=190)clr='var(--ht)';"
"else if(temp>=120)clr='var(--wm)';else if(temp>=40)clr='var(--ru)';"
"el.style.stroke=clr;elV.textContent=temp>0?temp.toFixed(1):'--'}"
"var sn={'offline':'Offline','idle':'Idle','printing':'Printing','paused':'Paused','error':'Error'};"
"function poll(){fetch('/api/status').then(function(r){return r.json()}).then(function(d){"
"var dt=document.getElementById('dot');"
"dt.className='dot '+(d.state==='printing'?'run':d.state==='offline'?'off':'ok');"
"document.getElementById('ip-txt').textContent="
"d.state==='offline'?'Waiting...':'http://'+location.host;"
"updateRing(document.getElementById('nr'),d.nozzle_actual,300,"
"document.getElementById('nv'),document.getElementById('nt'));"
"document.getElementById('nt').textContent="
"d.nozzle_target>0?d.nozzle_target.toFixed(1)+'C':'';"
"updateRing(document.getElementById('br'),d.bed_actual,120,"
"document.getElementById('bv'),document.getElementById('bt'));"
"document.getElementById('bt').textContent="
"d.bed_target>0?d.bed_target.toFixed(1)+'C':'';"
"var stEl=document.getElementById('state-txt');"
"stEl.textContent=sn[d.state]||d.state;"
"stEl.className='v s-'+d.state;"
"document.getElementById('file-name').textContent=d.file||'';"
"var pct=d.progress||0;"
"document.getElementById('prog-fill').style.width=pct+'%';"
"var pf=document.getElementById('prog-fill');"
"pf.className=d.state==='printing'?'run':'';"
"document.getElementById('prog-pct').textContent=pct+'%';"
"document.getElementById('lines-info').textContent="
"d.lines_sent+'/'+d.lines_total;"
"if(d.state==='printing'){"
"if(!prt)prt=Date.now();elt=Math.floor((Date.now()-prt)/1000);"
"var eta=elt>0&&pct>0?Math.floor(elt*100/pct)-elt:0;"
"document.getElementById('time-info').textContent="
"Math.floor(elt/60)+'m'+('0'+(elt%60)).slice(-2)+'s';"
"document.getElementById('eta-info').textContent="
"eta>0?'ETA:'+Math.floor(eta/60)+'m'+('0'+(eta%60)).slice(-2)+'s':'';"
"}else{prt=0;elt=0;"
"document.getElementById('time-info').textContent='--';"
"document.getElementById('eta-info').textContent=''}"
"}).catch(function(e){"
"document.getElementById('dot').className='dot off';"
"document.getElementById('ip-txt').textContent='Connection failed'});}"
"setInterval(poll,2000);poll();"
"</script></body></html>";

static const char *JSON_OK     = "{\"ok\":true,\"msg\":\"%s\"}";
static const char *JSON_ERR    = "{\"ok\":false,\"error\":\"%s\"}";
static const char *JSON_STATUS =
    "{\"state\":\"%s\",\"nozzle_actual\":%.1f,\"nozzle_target\":%.1f,"
    "\"bed_actual\":%.1f,\"bed_target\":%.1f,"
    "\"progress\":%d,\"lines_sent\":%d,\"lines_total\":%d,\"file\":\"%s\"}";
