#pragma once

static const char *WEB_INDEX_HTML =
"<!DOCTYPE html><html lang=\"zh\"><head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Switch Printer</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#eee;min-height:100vh}"
".head{background:#16213e;padding:12px 16px;text-align:center;border-bottom:2px solid #0f3460}"
".head h1{font-size:1.2em;color:#e94560}"
".status{display:flex;gap:8px;padding:12px;flex-wrap:wrap;justify-content:center}"
".card{background:#16213e;border-radius:10px;padding:14px;flex:1;min-width:120px;text-align:center}"
".card .val{font-size:1.8em;font-weight:bold}"
".card .lbl{font-size:.75em;color:#888;margin-top:4px}"
".online{color:#4ecca3}.offline{color:#e94560}.printing{color:#f0c040}"
".actions{display:flex;gap:8px;padding:12px;flex-wrap:wrap;justify-content:center}"
"button{background:#0f3460;color:#eee;border:none;padding:12px 20px;border-radius:8px;font-size:1em;cursor:pointer}"
"button:active{background:#1a5276}button.danger{background:#e94560}button.go{background:#4ecca3;color:#000}"
".upload{padding:12px;text-align:center}"
".upload input{background:#16213e;color:#eee;padding:8px;border-radius:6px;border:1px solid #0f3460;width:100%;max-width:300px}"
".progress-bar{background:#0f3460;border-radius:10px;height:20px;margin:12px;overflow:hidden}"
".progress-bar div{background:#e94560;height:100%;transition:width .5s;border-radius:10px}"
".console{background:#0d0d1a;margin:12px;padding:10px;border-radius:8px;height:150px;overflow-y:auto;font-family:monospace;font-size:.8em}"
"@media(min-width:768px){.card{min-width:150px}.head h1{font-size:1.6em}}"
"</style></head><body>"
"<div class=\"head\"><h1>Switch 3D Printer</h1><p id=\"conn-status\" class=\"offline\">Waiting...</p></div>"
"<div class=\"status\">"
"<div class=\"card\"><div class=\"val\" id=\"nozzle\">--</div><div class=\"lbl\">Nozzle C</div></div>"
"<div class=\"card\"><div class=\"val\" id=\"bed\">--</div><div class=\"lbl\">Bed C</div></div>"
"<div class=\"card\"><div class=\"val\" id=\"progress\">0%</div><div class=\"lbl\">Progress</div></div>"
"<div class=\"card\"><div class=\"val\" id=\"state-text\">Offline</div><div class=\"lbl\">State</div></div>"
"</div>"
"<div class=\"progress-bar\"><div id=\"prog-fill\" style=\"width:0%\"></div></div>"
"<div class=\"actions\">"
"<button onclick=\"api('home')\">Home</button>"
"<button onclick=\"api('pause')\">Pause</button>"
"<button onclick=\"api('resume')\">Resume</button>"
"<button class=\"danger\" onclick=\"api('cancel')\">Stop</button>"
"</div>"
"<div class=\"actions\">"
"<button onclick=\"move('x',-10)\">X-10</button>"
"<button onclick=\"move('x',10)\">X+10</button>"
"<button onclick=\"move('y',-10)\">Y-10</button>"
"<button onclick=\"move('y',10)\">Y+10</button>"
"<button onclick=\"move('z',-1)\">Z-1</button>"
"<button onclick=\"move('z',1)\">Z+1</button>"
"<button class=\"go\" onclick=\"api('home')\">All Home</button>"
"</div>"
"<div class=\"upload\">"
"<input type=\"file\" id=\"gcode-file\" accept=\".gcode,.gco,.nc\">"
"<button class=\"go\" onclick=\"uploadFile()\">Upload and Print</button>"
"</div>"
"<div class=\"console\" id=\"console\">Waiting for printer connection...</div>"
"<script>"
"function api(cmd){fetch('/api/'+cmd).then(r=>r.json()).then(d=>{log(d.msg||d.error||cmd)})}"
"function move(axis,dist){fetch('/api/move?axis='+axis+'&dist='+dist).then(r=>r.json()).then(d=>log(d.msg))}"
"function log(m){var c=document.getElementById('console');c.textContent+=m+'\\n';c.scrollTop=c.scrollHeight}"
"function uploadFile(){var f=document.getElementById('gcode-file').files[0];if(!f)return;"
"var fd=new FormData();fd.append('file',f);log('Uploading: '+f.name);"
"fetch('/upload',{method:'POST',body:fd}).then(r=>r.json()).then(d=>log(d.msg||d.error))}"
"function poll(){fetch('/api/status').then(r=>r.json()).then(d=>{"
"document.getElementById('nozzle').textContent=d.nozzle_actual+'/'+d.nozzle_target;"
"document.getElementById('bed').textContent=d.bed_actual+'/'+d.bed_target;"
"document.getElementById('progress').textContent=d.progress+'%';"
"document.getElementById('prog-fill').style.width=d.progress+'%';"
"var st=document.getElementById('state-text');"
"st.textContent={'offline':'Offline','idle':'Idle','printing':'Printing','paused':'Paused','error':'Error'}[d.state]||d.state;"
"st.className=d.state==='printing'?'printing':d.state==='offline'?'offline':'online'})"
".catch(e=>{document.getElementById('conn-status').textContent='Connection failed'})}"
"setInterval(poll,2000);poll();"
"</script></body></html>";

static const char *JSON_OK     = "{\"ok\":true,\"msg\":\"%s\"}";
static const char *JSON_ERR    = "{\"ok\":false,\"error\":\"%s\"}";
static const char *JSON_STATUS =
    "{\"state\":\"%s\",\"nozzle_actual\":%.1f,\"nozzle_target\":%.1f,"
    "\"bed_actual\":%.1f,\"bed_target\":%.1f,"
    "\"progress\":%d,\"lines_sent\":%d,\"lines_total\":%d,\"file\":\"%s\"}";