#pragma once

// 嵌入式 Web UI — 暗色工业风仪表盘
// 自适应手机竖屏 + 电脑宽屏
static const char *WEB_INDEX_HTML =
"<!DOCTYPE html><html lang=\"zh\"><head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">"
"<title>Switch Printer</title>"
"<style>"
":root{--bg:#0f1119;--card:#181b29;--accent:#00e5ff;--warn:#ffab00;--danger:#ff1744;"
"--green:#00e676;--text:#c8ccd4;--dim:#5a6170;--radius:12px;--gap:10px}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;"
"background:var(--bg);color:var(--text);min-height:100vh;"
"display:flex;flex-direction:column;overflow-x:hidden}"
".header{background:linear-gradient(135deg,#1a1f35 0%,#0f1119 100%);"
"padding:16px;text-align:center;border-bottom:1px solid #252940;"
"display:flex;align-items:center;justify-content:center;gap:12px}"
".header .dot{width:12px;height:12px;border-radius:50%;background:var(--danger);"
"box-shadow:0 0 8px var(--danger);transition:all .3s}"
".header .dot.online{background:var(--green);box-shadow:0 0 12px var(--green)}"
".header .dot.printing{background:var(--accent);box-shadow:0 0 12px var(--accent);animation:pulse 1s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}"
".header h1{font-size:1rem;font-weight:600;letter-spacing:.05em}"
".header .ip{font-size:.7rem;color:var(--dim)}"

".gauges{display:grid;grid-template-columns:1fr 1fr;gap:var(--gap);padding:12px}"
".gauge{background:var(--card);border-radius:var(--radius);padding:16px;text-align:center;"
"border:1px solid #1e2233;position:relative}"
".gauge svg{width:100%;max-width:140px;margin:0 auto;display:block}"
".gauge .val{font-size:2rem;font-weight:700;margin-top: -10px}"
".gauge .lbl{font-size:.65rem;color:var(--dim);text-transform:uppercase;letter-spacing:.1em;margin-top:2px}"
".gauge .target{font-size:.7rem;color:var(--dim);margin-top:1px}"

".status-bar{display:flex;gap:var(--gap);padding:0 12px 12px}"
".stat{background:var(--card);border-radius:var(--radius);padding:12px 16px;flex:1;"
"text-align:center;border:1px solid #1e2233}"
".stat .val{font-weight:700;font-size:.9rem}"
".stat .lbl{font-size:.6rem;color:var(--dim);text-transform:uppercase;letter-spacing:.1em}"

".progress-section{padding:0 12px}"
".progress-bar{background:#1e2233;border-radius:20px;height:8px;margin:8px 0;overflow:hidden}"
".progress-bar div{background:linear-gradient(90deg,var(--accent),var(--green));"
"height:100%;border-radius:20px;transition:width .6s ease;min-width:2px}"
".progress-text{display:flex;justify-content:space-between;font-size:.7rem;color:var(--dim)}"

".controls{display:grid;grid-template-columns:repeat(4,1fr);gap:var(--gap);padding:12px}"
".controls button{background:var(--card);color:var(--text);border:1px solid #252940;"
"padding:12px 8px;border-radius:var(--radius);font-size:.75rem;cursor:pointer;"
"transition:all .15s;display:flex;flex-direction:column;align-items:center;gap:4px;"
"font-family:inherit;-webkit-tap-highlight-color:transparent}"
".controls button:active{transform:scale(.95);background:#252940}"
".controls button .icon{font-size:1.4rem}"
".controls .danger{color:var(--danger);border-color:rgba(255,23,68,.3)}"
".controls .danger:active{background:rgba(255,23,68,.15)}"
".controls .go{color:var(--green);border-color:rgba(0,230,118,.3)}"

".jog{display:grid;grid-template-columns:1fr 1fr 1fr;grid-template-rows:1fr 1fr 1fr;"
"gap:6px;padding:0 12px 12px;max-width:300px;margin:0 auto}"
".jog button{background:var(--card);color:var(--text);border:1px solid #252940;"
"padding:14px 8px;border-radius:var(--radius);font-size:.85rem;cursor:pointer;"
"font-family:inherit;-webkit-tap-highlight-color:transparent}"
".jog button:active{background:#252940}"
".jog .center{grid-column:2;grid-row:2;color:var(--dim);font-size:.7rem}"

".upload{padding:0 12px 12px;display:flex;gap:8px}"
".upload input{flex:1;background:var(--card);color:var(--text);padding:10px 12px;"
"border-radius:var(--radius);border:1px solid #252940;font-size:.8rem;font-family:inherit}"
".upload input::file-selector-button{background:#252940;color:var(--text);"
"border:none;padding:6px 14px;border-radius:6px;cursor:pointer;font-family:inherit;margin-right:8px}"

".log{background:#0a0c14;margin:12px;padding:10px;border-radius:8px;height:120px;"
"overflow-y:auto;font-family:'SF Mono',Monaco,monospace;font-size:.65rem;"
"color:var(--dim);border:1px solid #1a1d2a;line-height:1.5}"
".log .ts{color:#455}"

".file-name{padding:0 12px;font-size:.7rem;color:var(--accent);text-align:center;"
"white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"

"@media(min-width:768px){"
"body{max-width:600px;margin:0 auto}"
".gauges{grid-template-columns:repeat(2,1fr);max-width:400px;margin:0 auto}"
".controls button{font-size:.85rem}"
"}"

".st-idle{color:var(--green)}.st-printing{color:var(--accent)}"
".st-paused{color:var(--warn)}.st-error{color:var(--danger)}.st-offline{color:var(--dim)}"
"</style></head><body>"

"<div class=\"header\">"
"<div class=\"dot\" id=\"dot\"></div>"
"<div><h1>Switch 3D Printer</h1><div class=\"ip\" id=\"conn-text\">等待连接...</div></div>"
"</div>"

"<div class=\"gauges\">"
"<div class=\"gauge\"><div class=\"val\" id=\"nozzle-val\">--</div>"
"<div class=\"lbl\">喷头 °C</div><div class=\"target\" id=\"nozzle-t\"></div></div>"
"<div class=\"gauge\"><div class=\"val\" id=\"bed-val\">--</div>"
"<div class=\"lbl\">热床 °C</div><div class=\"target\" id=\"bed-t\"></div></div>"
"</div>"

"<div class=\"status-bar\">"
"<div class=\"stat\"><div class=\"val st-offline\" id=\"state-txt\">离线</div><div class=\"lbl\">状态</div></div>"
"<div class=\"stat\"><div class=\"val\" id=\"size-txt\">--</div><div class=\"lbl\">大小</div></div>"
"</div>"

"<div class=\"file-name\" id=\"file-name\"></div>"
"<div class=\"progress-section\">"
"<div class=\"progress-bar\"><div id=\"prog-fill\" style=\"width:0%\"></div></div>"
"<div class=\"progress-text\"><span id=\"prog-pct\">0%</span><span id=\"prog-lines\"></span></div>"
"</div>"

"<div class=\"controls\">"
"<button onclick=\"api('home')\"><span class=\"icon\">🏠</span>归零</button>"
"<button onclick=\"api('pause')\"><span class=\"icon\">⏸</span>暂停</button>"
"<button onclick=\"api('resume')\"><span class=\"icon\">▶</span>恢复</button>"
"<button class=\"danger\" onclick=\"api('cancel')\"><span class=\"icon\">⏹</span>停止</button>"
"</div>"

"<div class=\"jog\">"
"<button style=\"grid-column:2;grid-row:1\" onclick=\"move('y',10)\">Y+</button>"
"<button style=\"grid-column:1;grid-row:2\" onclick=\"move('x',-10)\">X-</button>"
"<div class=\"center\">JOG</div>"
"<button style=\"grid-column:3;grid-row:2\" onclick=\"move('x',10)\">X+</button>"
"<button style=\"grid-column:2;grid-row:3\" onclick=\"move('y',-10)\">Y-</button>"
"</div>"
"<div class=\"controls\">"
"<button onclick=\"move('z',1)\">Z+1</button>"
"<button onclick=\"move('z',-1)\">Z-1</button>"
"<button onclick=\"api('home')\">全部归零</button>"
"</div>"

"<div class=\"upload\">"
"<input type=\"file\" id=\"gcode-file\" accept=\".gcode,.gco,.nc\">"
"<button class=\"go\" onclick=\"uploadFile()\">上传打印</button>"
"</div>"
"<div class=\"log\" id=\"log\">等待打印机连接...</div>"

"<script>"
"function api(cmd){fetch('/api/'+cmd).then(r=>r.json()).then(d=>{"
"log(d.msg||d.error||cmd)})}"
"function move(axis,dist){fetch('/api/move?axis='+axis+'&dist='+dist)"
".then(r=>r.json()).then(d=>log(d.msg))}"
"function uploadFile(){var f=document.getElementById('gcode-file').files[0];"
"if(!f)return;var fd=new FormData();fd.append('file',f);"
"log('上传: '+f.name+' ('+(f.size/1e6).toFixed(1)+' MB)');"
"fetch('/upload',{method:'POST',body:fd}).then(r=>r.json())"
".then(d=>log(d.msg||d.error))}"
"var logEl=document.getElementById('log');"
"function log(m){var t=new Date().toLocaleTimeString();"
"logEl.innerHTML+='<span class=\"ts\">'+t+'</span> '+m+'\\n';"
"logEl.scrollTop=logEl.scrollHeight;"
"if(logEl.children.length>200)logEl.firstChild.remove()}"
"var stateCls='st-offline';"
"function poll(){fetch('/api/status').then(r=>r.json()).then(d=>{"
"var nt=d.nozzle_actual,dm=document.getElementById('dot');"
"dm.className='dot '+(d.state==='printing'?'printing':d.state==='offline'?'':'online');"
"document.getElementById('conn-text').textContent="
"d.state==='offline'?'等待连接':'http://'+location.host;"
"document.getElementById('nozzle-val').textContent=nt.toFixed(1);"
"document.getElementById('bed-val').textContent=d.bed_actual.toFixed(1);"
"document.getElementById('nozzle-t').textContent=d.nozzle_target>0?'→'+d.nozzle_target.toFixed(1):'';"
"document.getElementById('bed-t').textContent=d.bed_target>0?'→'+d.bed_target.toFixed(1):'';"
"var stEl=document.getElementById('state-txt');"
"var sn={'offline':'离线','idle':'空闲','printing':'打印中','paused':'已暂停','error':'错误'};"
"stEl.textContent=sn[d.state]||d.state;"
"stEl.className='val st-'+d.state;"
"document.getElementById('file-name').textContent=d.file||'';"
"var pct=d.progress||0;"
"document.getElementById('prog-fill').style.width=pct+'%';"
"document.getElementById('prog-pct').textContent=pct+'%';"
"document.getElementById('prog-lines').textContent="
"d.lines_sent+' / '+d.lines_total;"
"var fsz=(d.lines_sent*50/1e6).toFixed(1);"
"document.getElementById('size-txt').textContent="
"d.state==='printing'?fsz+' MB':'--';"
"}).catch(function(e){document.getElementById('dot').className='dot';"
"document.getElementById('conn-text').textContent='连接失败'})}"
"setInterval(poll,2000);poll();"
"</script></body></html>";

static const char *JSON_OK     = "{\"ok\":true,\"msg\":\"%s\"}";
static const char *JSON_ERR    = "{\"ok\":false,\"error\":\"%s\"}";
static const char *JSON_STATUS =
    "{\"state\":\"%s\",\"nozzle_actual\":%.1f,\"nozzle_target\":%.1f,"
    "\"bed_actual\":%.1f,\"bed_target\":%.1f,"
    "\"progress\":%d,\"lines_sent\":%d,\"lines_total\":%d,\"file\":\"%s\"}";
